### PR TITLE
Add an option flag to allow using a pflash for firmware

### PR DESCRIPTION
**Pull request by carenas**
Provide  an escape hatch so the solution implemented with #43 could be used without introducing regressions by default.

Closes: #66

### CODE REVIEW

**Comment by heroin-moose** [comment]
Please see my [comment](https://github.com/hashicorp/packer-plugin-qemu/pull/43#issuecomment-1073002066).

**Review by nywilken — CHANGES_REQUESTED** [review]
@carenas thank you for working on this fix. The change looks good to be, and in-hindsight the approach we've should've taken. I didn't anticipate such failures. 

That said I made two small suggestions. The check `check-generate` job failed, which you can fix by running `make generate`. Please let me know if you need help pushing the changes.

**Comment by carenas** [comment]
I think I generated the files locally so I could test but intentionally omited them in the commit assuming they will be regenerated, but has been so long that I might had forgotten how, because now generate is throwing an error (using go1.18 darwin/amd64):

```
mapstructure-to-hcl2: qemu.[Config QemuImgArgs]: internal error: package "fmt" without types was imported from "github.com/hashicorp/packer-plugin-qemu/builder/qemu"
builder/qemu/config.go:2: running "packer-sdc": exit status 1
```

**Comment by carenas** [comment]
>  because now generate is throwing an error (using go1.18 darwin/amd64):

and it seems it is probably a bug in golang/go#37167, which was worked around by using go1.17 instead

**Comment by nywilken** [comment]
> I think I generated the files locally so I could test but intentionally omited them in the commit assuming they will be regenerated, but has been so long that I might had forgotten how, because `make generate` is throwing an error (using go1.18 darwin/amd64):
> 
> ```
> mapstructure-to-hcl2: qemu.[Config QemuImgArgs]: internal error: package "fmt" without types was imported from "github.com/hashicorp/packer-plugin-qemu/builder/qemu"
> builder/qemu/config.go:2: running "packer-sdc": exit status 1
> ```

Thanks for bubbling this up. I opened an issue on the Packer Plugin SDK for us to review.

**Pull request merged**
